### ISSUE TITLE
Impossible to save mask in LoadImage node on website

### ISSUE THREAD

**Issue by marom17** [get-salt-AI/SaltAI#19]
Hi,

I get the following error when a try to save the mask of the LoadImage node on the website:

Uncaught (in promise) DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at MaskEditorDialog.save (https://iframe.getsalt.ai/extensions/core/maskeditor.js:844:32)
    at HTMLButtonElement.<anonymous> (https://iframe.getsalt.ai/extensions/core/maskeditor.js:229:10)

Step to reproduce:
Create a new workflow on getsalt.ai
Create a LoadImage node
Upload an image
Create a mask
Click save mask
Nothing happen and an error is shown in the console

Tested on Firefox and Edge

**Comment by WAS-PlaiLabs** [comment]
A work around in the meantime would be to convert the mask to a image, and output with the SaltOutput node.
