### ISSUE TITLE
Install issue - 

### ISSUE THREAD

**Issue by RenderRift** [get-salt-AI/SaltAI#6]
I tried installing through comyfui-manager and I seem to get a couple of errors and it's not loading correctly. I've put the errors below:

`## Execute install/(de)activation script for 'C:\Users\<user>\SD\Packages\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI'
 Collecting llama-index-readers-web==0.1.6
   Using cached llama_index_readers_web-0.1.6-py3-none-any.whl.metadata (1.2 kB)
   Collecting chromedriver-autoinstaller<0.7.0,>=0.6.3 (from llama-index-readers-web==0.1.6)
   Using cached chromedriver_autoinstaller-0.6.4-py3-none-any.whl.metadata (2.1 kB)
 Collecting html2text<2021.0.0,>=2020.1.16 (from llama-index-readers-web==0.1.6)
   Using cached html2text-2020.1.16-py3-none-any.whl.metadata (4.3 kB)
  Collecting newspaper3k<0.3.0,>=0.2.8 (from llama-index-readers-web==0.1.6)
   Using cached newspaper3k-0.2.8-py3-none-any.whl.metadata (11 kB)
 Collecting playwright<2.0,>=1.30 (from llama-index-readers-web==0.1.6)
   Using cached playwright-1.42.0-py3-none-win_amd64.whl.metadata (3.5 kB)
  Collecting selenium<5.0.0,>=4.17.2 (from llama-index-readers-web==0.1.6)
   Using cached selenium-4.18.1-py3-none-any.whl.metadata (6.9 kB)
                             Collecting cssselect>=0.9.2 (from newspaper3k<0.3.0,>=0.2.8->llama-index-readers-web==0.1.6)
   Using cached cssselect-1.2.0-py2.py3-none-any.whl.metadata (2.2 kB)
 Collecting lxml>=3.6.0 (from newspaper3k<0.3.0,>=0.2.8->llama-index-readers-web==0.1.6)
   Using cached lxml-5.1.0-cp311-cp311-win_amd64.whl.metadata (3.6 kB)
 Collecting feedparser>=5.2.1 (from newspaper3k<0.3.0,>=0.2.8->llama-index-readers-web==0.1.6)
   Using cached feedparser-6.0.11-py3-none-any.whl.metadata (2.4 kB)
 Collecting tldextract>=2.0.1 (from newspaper3k<0.3.0,>=0.2.8->llama-index-readers-web==0.1.6)
   Using cached tldextract-5.1.1-py3-none-any.whl.metadata (11 kB)
 Collecting feedfinder2>=0.0.4 (from newspaper3k<0.3.0,>=0.2.8->llama-index-readers-web==0.1.6)
   Using cached feedfinder2-0.0.4.tar.gz (3.3 kB)
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   python setup.py egg_info did not run successfully.
[!]   exit code: 1
[!]
[!]   [6 lines of output]
[!]   Traceback (most recent call last):
[!]     File "<string>", line 2, in <module>
[!]     File "<pip-setuptools-caller>", line 34, in <module>
[!]     File "C:\Users\<user>\AppData\Local\Temp\pip-install-ku4lfves\feedfinder2_77127030452d4e118768f57e02e98ff5\setup.py", line 15, in <module>
[!]       import feedfinder2
[!]   ModuleNotFoundError: No module named 'feedfinder2'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!]
[!] Encountered error while generating package metadata.
[!]
[!] See above for output.
[!]
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.
install/(de)activation script failed: C:\Users\<user>\SD\Packages\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI`

And also this pops up:

`Traceback (most recent call last):
  File "C:\Users\<user>\SD\Packages\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\modules\node_importer.py", line 20, in import_module
    module = importlib.import_module(module_name, package=package_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\<user>\SD\Packages\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\SaltAI-Llama-Index\__init__.py", line 3, in <module>
    from .nodes_core import NODE_CLASS_MAPPINGS as nodes_core_classes
  File "C:\Users\<user>\SD\Packages\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\SaltAI-Llama-Index\nodes_core.py", line 46, in <module>
    from llama_index.readers.web import SimpleWebPageReader
ModuleNotFoundError: No module named 'llama_index.readers.web'
Import times for Salt.AI Node Modules:
   0.0 seconds: C:\Users\<user>\SD\Packages\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\api\stability_ai.py
   0.0 seconds: C:\Users\<user>\SD\Packages\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\io\input_output.py
   0.0 seconds: C:\Users\<user>\SD\Packages\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\SaltAI-Animation-Keyframing\__init__.py
   1.0 seconds (IMPORT FAILED): SaltAI-Llama-Index
Error: No module named 'llama_index.readers.web'
   0.0 seconds: C:\Users\<user>\SD\Packages\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\string\processing.py
   0.0 seconds: C:\Users\<user>\SD\Packages\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\utility\convert.py`

If I can provide anything else to help with please let me know. 

Thanks!

**Comment by WAS-PlaiLabs** [comment]
It looks like there was an error during the installation of the web readers for Llama-Index. It seems [feedfinder2](https://pypi.org/project/feedfinder2/) isn't present.

You could try to install directly to your portable environment the missing dependency. I'd start be removing SaltAI, and then running `C:\Users\<user>\SD\Packages\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe -m pip install feedfinder2`

After that has _hopefully_ succeeded, try to install SaltAI again via the Manager.

**Comment by RenderRift** [comment]
Thanks for the help! I think my Comfui Portable install was really messed up so I removed it and used a normal of comfy. 

I did run into some issues but they were fixed by manually installing the following: 

pip install llama-index
pip install llama-index-readers-notion
pip install llama-index-readers-web

Which seems to have it up and running now! Thank you
